/*
 * SPDX - FileCopyrightText: Copyright © 2025 Christian Günther <cg-ite@gmx.de>
 * SPDX - License - Identifier: GPL - 3.0 - or - later
 */

namespace TrackAndFieldResults.Seltec
{
    /// <summary>
    /// JsonClient for getting the results of the German Athletics Federation (DLV).
    /// You need an api-key from them to get access to the result
    /// database, see https://github.com/Deutscher-Leichtathletikverband/Interfaces?tab=readme-ov-file
    /// The client is generated by NSwagStudio with this schema
    /// https://ergebnisse.leichtathletik.de/swagger/v1/swagger.json
    /// </summary>
    public partial class SeltecAthonClient
    {
    }
}
